import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import { Inter } from "next/font/google";
import "./globals.css";

import { LoggedInHeader } from "./components/organisms/LoggedInHeader/LoggedInHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moonshake Admin Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <LoggedInHeader />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
