import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";

import "./globals.css";

import { LoggedInHeader } from "./components/organisms/LoggedInHeader/LoggedInHeader";

export const metadata: Metadata = {
  title: "Moonshake Admin Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <LoggedInHeader />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
